---
title: "Reproducible research week2"
author: "Azat Gabdolla"
date: '29 октября 2018 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages(suppressWarnings(library(data.table)))
suppressMessages(suppressWarnings(library(lattice)))
suppressMessages(suppressWarnings(library(ggplot2)))
```


```{r}
setwd("~/Edu/Reproducible research")

activity <- setDT(read.csv("activity.csv",sep = ",", header = TRUE, na.strings = c("NA", " ", '#DIV/0!')))
```

##Mean total number steps taken per day
Total steps taken per day
```{r}
activity[!is.na(steps) , sum(steps), date]
```
Histogram of  
```{r}
histogram(activity[!is.na(steps) , sum(steps), date][,V1], xlab = c("total steps"), ylab = c("percentage") )
```
Mean and median of total steps taken per day
```{r}
activity[!is.na(steps) , sum(steps), date][,mean(V1)]
activity[!is.na(steps) , sum(steps), date][,median(V1)]
```

##Average daily activity pattern

```{r}
tsactivity <-  aggregate(activity$steps, by = list(activity$interval), mean, na.rm=TRUE)
tsactivity <- setDT(tsactivity)
setnames(tsactivity, c("interval" , "mean.steps"))
ggplot(tsactivity,  aes(x=interval, y = mean.steps))+geom_line()
```

## Imputing Missing values
```{r}
paste( activity[is.na(steps),.N], "of cells are missing in steps")
```


```{r}
tsactivity[mean.steps == max(mean.steps), .(interval)]
```

When interval is 835 the maximum mean steps occur

```{r}
activity[!is.na(steps) & ! interval == 0, mean(steps/interval)]
# 0.0350705
activity[is.na(steps), steps := activity[!is.na(steps) & ! interval == 0, mean(steps/interval)]*interval]

```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
  activity[,date:= as.Date(date)]

activity$weekdays <- as.factor(ifelse(weekdays(activity$date) %in% c("суббота","воскресенье"), "weekend", "weekday"))

```

```{r}
steps_interval_mean <- aggregate(steps ~ interval + weekdays, FUN=mean, 
                                    data=activity)

xyplot(steps ~ interval | weekdays, 
       data = steps_interval_mean, 
       type = "l", 
       layout = c(1, 2), 
       xlab = "Interval", 
       ylab = "Number of steps taken")
```


